workspace(name = "EigenDemo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Eigen
http_archive(
    name = "eigen",
    sha256 = "0215c6593c4ee9f1f7f28238c4e8995584ebf3b556e9dbf933d84feb98d5b9ef",
    build_file = "//:eigen.BUILD",
    strip_prefix = "eigen-3.3.8",
    urls = [
        "https://gitlab.com/libeigen/eigen/-/archive/3.3.8/eigen-3.3.8.tar.bz2",
    ],
)
# http_archive(
#     name = "eigen",
#     build_file = "//:eigen.BUILD",
#     urls = ["https://gitlab.com/libeigen/eigen/-/archive/master.zip"],
#     sha256 = "81592d7efee658b55b3fe0c648f4c5a8c103c7b22691d0d13d4b3e40e9d7",
#     strip_prefix="eigen-eigen-c5e90d9e764e"
# )